# Configuración global para Prometheus
global:
  scrape_interval: 15s  # Intervalo en el que Prometheus recogerá las métricas de los servicios

# Configuración de los trabajos de scrape (recolección de métricas)
scrape_configs:

  # Configuración para recolectar métricas de Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']  # Dirección de Redis en Docker, puerto 6379

  # Configuración para recolectar métricas de Prometheus mismo (si deseas monitorear a Prometheus)
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Dirección del servidor de Prometheus, puerto 9090


  - job_name: 'eureka-server'
    static_configs:
      - targets: ['eureka-server:8761']  # Dirección de Eureka Server, puerto 8761

 

  # Configuración para recolectar métricas de "MySQL" (si estás usando Prometheus Exporter para MySQL)
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysqldb:3306']  # Dirección de MySQL, puerto 3306
    metrics_path: '/metrics'  # Especifica la ruta de las métricas si estás usando un exporter

  
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']  
