spring:
  config:
    import: "configserver:http://config-server:8888"
  application:
    name: historial-clinico-service

server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true